---
title: "Answer to stackoverflow questions on hexadecimals to character"
author: "Pep Porrà"
date: '2023-01-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Stackoverflow

(https://stackoverflow.com/questions/29251934/how-to-convert-a-hex-string-to-text-in-r)

```{r}
s <- '1271763355662E324375203137'
sc <- unlist(strsplit(s, ""))
i1 <- (1:nchar(s)) %% 2 == 1
# pairs of characters
s_pairs1 <- paste0(sc[i1], sc[!i1])
# pairs of characters understood as hexadecimals
s_pairs2 <- paste0('0x', sc[i1], sc[!i1])
s_hex1 <- s_pairs1 |> as.hexmode() 
s_hex2 <- s_pairs2 |> as.hexmode()
all(s_hex1 == s_hex2)
# Turn hexadecimals into raw bytes
s_raw1 <- s_hex1 |> as.raw()
s_raw2 <- s_pairs1 |> as.raw()
s_raw3 <- s_pairs2 |> as.raw()
s_raw2bis <- s_pairs1 |> strtoi(base = 16L) |> as.raw()
# filter non printable character integer value >= 32 ("0x20")
result <- rawToChar(s_raw1[s_raw1 >= as.raw("0x20")])
result
```
<!-- 

#An alternative way that separates the two parts involved:

#1. Turn the initial string into a vector of bytes (with values as hexadecimals)
#2. Convert those raw bytes into characters (excluding any not printable)


#Part 1:


s <- '1271763355662E324375203137'
sc <- unlist(strsplit(s, ""))
i1 <- (1:nchar(s)) %% 2 == 1
# vector of bytes (as character)
s_pairs1 <- paste0(sc[i1], sc[!i1])
# make explicit it is a series of hexadecimals bytes
s_pairs2 <- paste0("0x", s_pairs1)
head(s_pairs2)


#Part 2:


s_raw1 <- as.raw(s_pairs2) 
# filter non printable values (ascii < 32 = 0x20)
s_raw2 <- s_raw1[s_raw1 >= as.raw("0x20")]
rawToChar(s_raw2)


#WE could also use `as.hexmode()` function to turn s_pairs1 into a vector of
#hexadecimals


s_pairs2 <-  as.hexmode(s_pairs1)
head(s_pairs2)

-->



(https://stackoverflow.com/questions/66639163/convert-from-hexadecimal-to-unicode-in-r-language)

```{r}
print_series <- function(s){
  cat("Class of series: ", class(s), "\n")
  cat("Sequence of integers/hexadecimals: ", s, "\n")
## generate the sequence on character
  cat("Sequence of characters: ", rawToChar(as.raw(s)), "\n")
  cat(rep("-", 10), "\n", sep = "")
}

## Sequence of integers
seq_ex <- 92:96
print_series(seq_ex)

## using hexadecimals sequences
seq_hex1 <- as.hexmode(sprintf("%x", seq_ex))
print_series(seq_hex1)

## Alternative 1
seq_hex2 <- paste0("0x", seq_hex1)
print_series(seq_hex2)

## Alternatives 2
seq_hex3 <- as.raw(seq_ex)
print_series(seq_hex3)

## From hexadecimals to characters through integers
seq_ex2 <- strtoi(seq_hex1, base = 16L) 
print_series(seq_ex2)
```

Answer: 

```{r}
x <- "\u005C"
y <- "005C"

eq_char_from_s <- function(s){
  rawToChar(as.raw(strtoi(y, 16L)))
}

z <- eq_char_from_s(y)

x == z
print(z)

```
